[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.4.1"
  name = "police_check_api"
  org = "pasidaleed"
  version = "0.1.0"

[[platform.java11.dependency]]
groupId = "org.postgresql"
artifactId = "postgresql"
version = "42.2.20"